name: Add Member to Repository

on:
  push:
    branches:
      - main

# on:
#   pull_request:
#     types: [closed]
#     branches:
#       - main
#     paths:
#       - 'COLLABORATOR.txt'
#       - 'scripts/**'
jobs:
  add-collaborator:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write
      packages: write
      repository-projects: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
        with:
          gh-cli-version: 2.32.0 # optional, see action.yml for current default

      - name: Add member to repository
        run: |
          ./scripts/add-collaborator-to-repository.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        

